<a href="https://colab.research.google.com/github/GANGADHAR99890/AI-Voice-Assistant/blob/main/RAG_system.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install sentence-transformers faiss-cpu openai pypdf

Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (5.5.1)
Collecting faiss-cpu
  Downloading faiss_cpu-1.14.3-cp310-abi3-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (7.8 kB)
Requirement already satisfied: openai in /usr/local/lib/python3.12/dist-packages (2.41.0)
Collecting pypdf
  Downloading pypdf-6.13.3-py3-none-any.whl.metadata (7.2 kB)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (5.10.2)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.18.0)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.11.0+cpu)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.0.2)
Requirement already satisfied: scikit-learn>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: tqdm>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.67.3)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from faiss-cpu) (26.2)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from openai) (4.13.0)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from openai) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from openai) (0.28.1)
Requirement already satisfied: jiter<1,>=0.10.0 in /usr/local/lib/python3.12/dist-packages (from openai) (0.15.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from openai) (2.12.3)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from openai) (1.3.1)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5,>=3.5.0->openai) (3.18)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->openai) (2026.5.20)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->openai) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai) (0.16.0)
Requirement already satisfied: click>=8.4.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (8.4.1)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (3.29.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (1.5.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (6.0.3)
Requirement already satisfied: typer<0.26.0,>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.25.1)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai) (0.4.2)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (3.6.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.8.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (0.0.4)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (0.1.2)
Downloading faiss_cpu-1.14.3-cp310-abi3-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (18.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.5/18.5 MB 22.1 MB/s eta 0:00:00
Downloading pypdf-6.13.3-py3-none-any.whl (347 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 347.3/347.3 kB 10.2 MB/s eta 0:00:00
Installing collected packages: pypdf, faiss-cpu
Successfully installed faiss-cpu-1.14.3 pypdf-6.13.3

In [4]:
import pandas as pd

test_df = pd.read_csv("/content/test.csv")

print("Shape:", test_df.shape)
print(test_df.head())

Shape: (140, 3)
   id                                           question  \
0   1  Under DPM 2025 Volume I, what authority level ...
1   2  According to DPM 2025 Volume II, what should h...
2   3  How does DFPDS Booklet 2024 support compliance...
3   4  What governance or procedural guidance from Na...
4   5  Which escalation principle in Navy Regulations...

                                            contexts
0  DPM 2025 Volume I defines authority boundaries...
1  DPM 2025 Volume II defines authority boundarie...
2  DFPDS Booklet 2024 defines authority boundarie...
3  Navy Regulations Part I defines authority boun...
4  Navy Regulations Part II defines authority bou...

In [5]:
import os

files = sorted(os.listdir("/content"))

for f in files:
    print(f)

.config
.ipynb_checkpoints
defence-rag-procurement-policy-reasoning-challenge.zip
metaData.csv
sample_data
sample_submission.csv
test.csv

In [6]:
import pandas as pd

meta = pd.read_csv("/content/metaData.csv")

print("Shape:", meta.shape)

print("\nColumns:")
print(meta.columns.tolist())

meta.head()

Shape: (1668, 5)

Columns:
['chunk_id', 'document', 'section', 'text', 'topic']

,chunk_id,document,section,text,topic
0,Delegation_of_Financial_Powers_Rules_2024_Book...,Delegation_of_Financial_Powers_Rules_2024_Book...,GOVERNMENT OF INDIA MINISTRY OF FINANCE DEPART...,GOVERNMENT OF INDIA\nMINISTRY OF FINANCE\nDEPA...,financial powers
1,Delegation_of_Financial_Powers_Rules_2024_Book...,Delegation_of_Financial_Powers_Rules_2024_Book...,Preface,"DELEGATION OF FINANCIAL POWERS RULES, 2024\nMI...",financial powers
2,Delegation_of_Financial_Powers_Rules_2024_Book...,Delegation_of_Financial_Powers_Rules_2024_Book...,Index,"DELEGATION OF FINANCIAL POWERS RULES, 2024\nMI...",financial powers
3,Delegation_of_Financial_Powers_Rules_2024_Book...,Delegation_of_Financial_Powers_Rules_2024_Book...,Item 18 Trading operations 19,Sr. No. PAGE\n18. Trading operations 19\n19. D...,financial powers
4,Delegation_of_Financial_Powers_Rules_2024_Book...,Delegation_of_Financial_Powers_Rules_2024_Book...,Rule 1 Short title and commencement-,"DELEGATION OF FINANCIAL POWERS RULES, 2024\nMI...",financial powers

In [11]:
import pandas as pd

meta = pd.read_csv("/content/metaData.csv")

print(meta.shape)
meta.head()

(1668, 5)

,chunk_id,document,section,text,topic
0,Delegation_of_Financial_Powers_Rules_2024_Book...,Delegation_of_Financial_Powers_Rules_2024_Book...,GOVERNMENT OF INDIA MINISTRY OF FINANCE DEPART...,GOVERNMENT OF INDIA\nMINISTRY OF FINANCE\nDEPA...,financial powers
1,Delegation_of_Financial_Powers_Rules_2024_Book...,Delegation_of_Financial_Powers_Rules_2024_Book...,Preface,"DELEGATION OF FINANCIAL POWERS RULES, 2024\nMI...",financial powers
2,Delegation_of_Financial_Powers_Rules_2024_Book...,Delegation_of_Financial_Powers_Rules_2024_Book...,Index,"DELEGATION OF FINANCIAL POWERS RULES, 2024\nMI...",financial powers
3,Delegation_of_Financial_Powers_Rules_2024_Book...,Delegation_of_Financial_Powers_Rules_2024_Book...,Item 18 Trading operations 19,Sr. No. PAGE\n18. Trading operations 19\n19. D...,financial powers
4,Delegation_of_Financial_Powers_Rules_2024_Book...,Delegation_of_Financial_Powers_Rules_2024_Book...,Rule 1 Short title and commencement-,"DELEGATION OF FINANCIAL POWERS RULES, 2024\nMI...",financial powers

In [12]:
test = pd.read_csv("/content/test.csv")

print(test.shape)
test.head()

(140, 3)

,id,question,contexts
0,1,"Under DPM 2025 Volume I, what authority level ...",DPM 2025 Volume I defines authority boundaries...
1,2,"According to DPM 2025 Volume II, what should h...",DPM 2025 Volume II defines authority boundarie...
2,3,How does DFPDS Booklet 2024 support compliance...,DFPDS Booklet 2024 defines authority boundarie...
3,4,What governance or procedural guidance from Na...,Navy Regulations Part I defines authority boun...
4,5,Which escalation principle in Navy Regulations...,Navy Regulations Part II defines authority bou...

In [15]:
!pip install -q sentence-transformers faiss-cpu

In [16]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer(
    "BAAI/bge-small-en-v1.5"
)

texts = meta["text"].fillna("").tolist()

print("Total chunks:", len(texts))

embeddings = model.encode(
    texts,
    normalize_embeddings=True,
    show_progress_bar=True
)

print("Embeddings created:", len(embeddings))

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:112: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md:   0%|          | 0.00/94.8k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/52.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/743 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/133M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/366 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/711k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/125 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Total chunks: 1668

Batches:   0%|          | 0/53 [00:00<?, ?it/s]

Embeddings created: 1668

In [17]:
import faiss
import numpy as np

embeddings = np.array(
    embeddings
).astype("float32")

index = faiss.IndexFlatIP(
    embeddings.shape[1]
)

index.add(embeddings)

print("Indexed:", index.ntotal)

Indexed: 1668

In [19]:
def retrieve(question, k=5):

    q_emb = model.encode(
        [question],
        normalize_embeddings=True
    )

    scores, ids = index.search(
        np.array(q_emb).astype("float32"),
        k
    )

    return meta.iloc[ids[0]][
        ["document","section","text"]
    ]

In [20]:
question = test.iloc[0]["question"]

print(question)

retrieve(question)

Under DPM 2025 Volume I, what authority level generally handles procurement approval within delegated limits?

,document,section,text
144,DPM-2025-VOLUME-I.pdf,Chapter 1,(1)\nDPM - 2025\nCHAPTER 1\nINTRODUCTION\n1.1 ...
436,DPM-2025-VOLUME-II.pdf,DPM - 2025 (Vol. II)Appendices and Forms,DPM - 2025 (Vol. II) Appendices and Forms\n(8)...
322,DPM-2025-VOLUME-I.pdf,(179),(179)\nDPM - 2025\nagency on Single Tender Enq...
156,DPM-2025-VOLUME-I.pdf,(13),(13)\nDPM - 2025\nwill take up the matter with...
448,DPM-2025-VOLUME-II.pdf,DPM - 2025 (Vol. II)Appendices and Forms,DPM - 2025 (Vol. II) Appendices and Forms\n(20...

In [21]:
!pip install -q transformers accelerate sentencepiece

In [22]:
from transformers import pipeline

generator = pipeline(
    "text2text-generation",
    model="google/flan-t5-base"
)

print("Model loaded")

config.json:   0%|          | 0.00/1.40k [00:00<?, ?B/s]

KeyError: "Unknown task text2text-generation, available tasks are ['any-to-any', 'audio-classification', 'automatic-speech-recognition', 'depth-estimation', 'document-question-answering', 'feature-extraction', 'fill-mask', 'image-classification', 'image-feature-extraction', 'image-segmentation', 'image-text-to-text', 'keypoint-matching', 'mask-generation', 'ner', 'object-detection', 'sentiment-analysis', 'table-question-answering', 'text-classification', 'text-generation', 'text-to-audio', 'text-to-speech', 'token-classification', 'video-classification', 'zero-shot-audio-classification', 'zero-shot-classification', 'zero-shot-image-classification', 'zero-shot-object-detection']"

In [23]:
import traceback

try:
    from transformers import pipeline

    generator = pipeline(
        "text2text-generation",
        model="google/flan-t5-base"
    )

    print("Loaded")
except Exception as e:
    traceback.print_exc()

Traceback (most recent call last):
  File "/tmp/ipykernel_1438/255949411.py", line 6, in <cell line: 0>
    generator = pipeline(
                ^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/transformers/pipelines/__init__.py", line 945, in pipeline
    normalized_task, targeted_task, task_options = check_task(task)
                                                   ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/transformers/pipelines/__init__.py", line 357, in check_task
    return PIPELINE_REGISTRY.check_task(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/transformers/pipelines/base.py", line 1340, in check_task
    raise KeyError(f"Unknown task {task}, available tasks are {self.get_supported_tasks()}")
KeyError: "Unknown task text2text-generation, available tasks are ['any-to-any', 'audio-classification', 'automatic-speech-recognition', 'depth-estimation', 'document-question-answering', 'feature-extraction', 'fill-mask', 'image-classification', 'image-feature-extraction', 'image-segmentation', 'image-text-to-text', 'keypoint-matching', 'mask-generation', 'ner', 'object-detection', 'sentiment-analysis', 'table-question-answering', 'text-classification', 'text-generation', 'text-to-audio', 'text-to-speech', 'token-classification', 'video-classification', 'zero-shot-audio-classification', 'zero-shot-classification', 'zero-shot-image-classification', 'zero-shot-object-detection']"

In [24]:
from transformers import pipeline

generator = pipeline(
    "text2text-generation",
    model="google/flan-t5-small",
    framework="pt"
)

config.json:   0%|          | 0.00/1.40k [00:00<?, ?B/s]

KeyError: "Unknown task text2text-generation, available tasks are ['any-to-any', 'audio-classification', 'automatic-speech-recognition', 'depth-estimation', 'document-question-answering', 'feature-extraction', 'fill-mask', 'image-classification', 'image-feature-extraction', 'image-segmentation', 'image-text-to-text', 'keypoint-matching', 'mask-generation', 'ner', 'object-detection', 'sentiment-analysis', 'table-question-answering', 'text-classification', 'text-generation', 'text-to-audio', 'text-to-speech', 'token-classification', 'video-classification', 'zero-shot-audio-classification', 'zero-shot-classification', 'zero-shot-image-classification', 'zero-shot-object-detection']"

In [25]:
def rag_answer(question):

    retrieved = retrieve(question)

    answer = retrieved.iloc[0]["text"]

    source = retrieved.iloc[0]["document"]

    return answer, source

In [27]:
def retrieve(question, k=3):

    q_emb = model.encode(
        [question],
        normalize_embeddings=True
    )

    scores, ids = index.search(
        np.array(q_emb).astype("float32"),
        k
    )

    return meta.iloc[ids[0]]

In [28]:
retrieve(test.iloc[0]["question"])

,chunk_id,document,section,text,topic
144,DPM-2025-VOLUME-I_p0015,DPM-2025-VOLUME-I.pdf,Chapter 1,(1)\nDPM - 2025\nCHAPTER 1\nINTRODUCTION\n1.1 ...,procurement
436,DPM-2025-VOLUME-II_p0015,DPM-2025-VOLUME-II.pdf,DPM - 2025 (Vol. II)Appendices and Forms,DPM - 2025 (Vol. II) Appendices and Forms\n(8)...,procurement
322,DPM-2025-VOLUME-I_p0193,DPM-2025-VOLUME-I.pdf,(179),(179)\nDPM - 2025\nagency on Single Tender Enq...,procurement

In [29]:
print(test.iloc[0]["question"])

Under DPM 2025 Volume I, what authority level generally handles procurement approval within delegated limits?

In [30]:
print(meta.iloc[144]["text"])

(1)
DPM - 2025
CHAPTER 1
INTRODUCTION
1.1 Short Title and Commencement
1.1.1 This Manual shall be called the Defence Procurement Manual,
2025 (DPM 2025, for short).
1.1.2 This Manual, containing principles and procedures relating to
revenue procurement of goods and services for the Defence
Services, Organisations and Establishments, laid down in terms
of Rule 142 of the General Financial Rules (GFRs) 2017 shall
come into force with effect from 1/11/2025.
1.1.3 All ongoing cases of procurement in which Requests for Proposal
(RFP) have already been issued, may continue to be regulated by
the provisions of the DPM 2009 as amended vide from time to
time.
1.2 Scope and Applicability
1.2.1 The principles and procedures contained in this Manual are to
be followed by all wings of the Ministry of Defence (MoD) and
the Defence Services as well as all Organisations including the
Indian Coast Guard (ICG) and Jammu & Kashmir Light Infantry
(JAKLI), and all Headquarters and subordinate authorities
in the Commands/equivalent in other Organisations, lower
formations, establishments and units there under at all levels,
and shall cover procurement of all goods and services including
medical equipment, other than Entitled Rations, Works and
Land, classified as Revenue Expenditure and booked under the
Revenue Budget Heads, apart from any other type of purchases
to which the provisions are made specifically applicable. The
Defence Research and Development Organisation (DRDO) and
the Defence Public Sector Undertakings (DPSUs) will, however,
continue to follow their own procurement procedure.
1.2.2 The procedure laid down in this Manual shall also be applicable
to the following: -
(a) Procurement of medical equipment under the Capital Budget
Head (apart from medical equipment under the Revenue Budget
Heads already covered under Paragraph 1.2.1 above).
(b) Procurements made by the Defence Services/ other

In [31]:
print(meta.iloc[322]["text"])

(179)
DPM - 2025
agency on Single Tender Enquiry basis. In case any other vendors/
firms are also permitted to respond to RFPs in addition to the
government designated agencies, such cases may be processed
on competitive basis in accordance with the L TE powers of CFAs.
7.23.2 Procurements Governed by General Contracts . In case of
procurements under Long-term General agreements/ Umbrella
contracts/ Main agreements/IGAs between the Government of
India and the Government of the country concerned as defined in
Para 1.3.20, provisions of such contracts/ agreements will prevail
over provisions of this Manual with regard to contract finalisation.
Other aspects of the procurement/contract which are not specified
in the Long-term General Agreements/ Umbrella Contracts/ Main
Agreements/IGAs etc. may be finalised duly considering provisions
stated in this Manual.
7.23.3 Urgent Procurement Through Indian Embassies Abroad. Spares/
components that are required urgently from sources abroad may
be procured through the Indian Embassies/ High Commissions.
On obtaining Acceptance of Necessity and approval of RM or any
other competent authority as may be designated by MoD from
time to time (as per Paragraph 7.1), an urgent indent should be
forwarded to the Embassy concerned for procurement under
the financial powers of the Commercial or Defence Attaché (DA)
concerned. The Attaché concerned should register the indent
and obtain quotes. The Attache will accord expenditure sanction
with concurrence of IFA, who may be Counsellor-coord in Indian
Embassy or any other authority nominated by Indian Ambassador
in that country. In case the quotes received are higher than the
delegated financial powers of the DA and the vendor does not
agree to reduce the cost, the case should be referred to the Service
HQs/ Department concerned of the Ministry of Defence for seeking
Expenditure Angle Sanction of the appropriate CFA.
7.23.4 Procurement of goods/ services of foreign origin from indigenous
firms/ suppliers shall be treated as import purchases in the
following cases:-
(a) Where the movement of goods/ supply of services from the
foreign country to India is occasioned directly as a result of
the sale.
(b) Where there is a privity of contract between the foreign supplier
and the Defence Department/ purchaser.
CHAPTER 7

In [32]:
print(meta.iloc[436]["text"])

DPM - 2025 (Vol. II) Appendices and Forms
(8)
Annexure-I
(Refers to Paragraphs 1 and 2
of Appendix A)
COMPETENT AUTHORITY AND PROCEDURE FOR REGISTRATION
A. The Competent Authority for the purpose of registration under this order shall be/
continue to be the Registration Committee constituted by the Department for Promotion
of Industry and Internal Trade (DPIIT)*. [This Committee was already constituted under
Order (Public Procurement) No. 1].
B. The Registration Committee shall have the following members*:
(i) An officer, not below the rank of Joint Secretary, designated for this purpose by
DPIIT, who shall be the Chairman;
(ii) Officers (ordinarily not below the rank of Joint Secretary) representing the Ministry
of Home Affairs, Ministry of External Affairs, and of those Departments whose
sectors are covered by applications under consideration;
(iii) Any other officer whose presence is deemed necessary by the Chairman of the
Committee.
(iv) With effect from 01.04.2023, an officer (ordinarily not below the rank of Joint
Secretary) representing the National Security Council Secretariat.
C. DPIIT shall lay down the method of application, format etc. for such bidders as covered
by the Order.
D. On receipt of an application seeking registration from a bidder covered by Para 2 and 3 of
this order, the Competent Authority shall first seek political and security clearances from
the Ministry of External Affairs and Ministry of Home Affairs, as per guidelines issued
from time to time. Registration shall not be given unless political and security clearance
have both been received.
E. The Ministry of External Affairs and Ministry of Home Affairs may issue guidelines for
internal use regarding the procedure for scrutiny of such applications by them.
F. The decision of the Competent Authority, to register such bidder may be for all kinds of
tenders or for a specified type(s) of goods or services, and may be for a specified or
unspecified duration of time, as deemed fit. The decision of the Competent Authority
shall be final.
G. Registration granted by the Competent Authority of the Government of India shall be
valid not only for procurement by the Central Government and its bodies specified in
para 6 of this order, but also for procurement by State Governments and their agencies/
public enterprises etc. No fresh registration at the State level shall be required.

In [36]:
import pandas as pd
import numpy as np
import faiss
import pickle

from sentence_transformers import SentenceTransformer

print("Loading corpus...")

meta = pd.read_csv("metaData.csv")

texts = meta["text"].fillna("").tolist()

model = SentenceTransformer(
    "BAAI/bge-small-en-v1.5"
)

print("Creating embeddings...")

embeddings = model.encode(
    texts,
    normalize_embeddings=True,
    show_progress_bar=True
)

embeddings = np.array(
    embeddings
).astype("float32")

index = faiss.IndexFlatIP(
    embeddings.shape[1]
)

index.add(embeddings)

faiss.write_index(
    index,
    "faiss.index"
)

meta.to_pickle(
    "metadata.pkl"
)

print("Index built successfully")

Loading corpus...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Creating embeddings...

Batches:   0%|          | 0/53 [00:00<?, ?it/s]

KeyboardInterrupt:

In [37]:
import pandas as pd
import numpy as np
import faiss

from sentence_transformers import SentenceTransformer

# Load corpus
meta = pd.read_csv("metaData.csv")

texts = meta["text"].fillna("").tolist()

# Embedding model
model = SentenceTransformer(
    "BAAI/bge-small-en-v1.5"
)

# Create embeddings
embeddings = model.encode(
    texts,
    normalize_embeddings=True
)

embeddings = np.array(
    embeddings
).astype("float32")

# Build FAISS index
index = faiss.IndexFlatIP(
    embeddings.shape[1]
)

index.add(embeddings)

print("RAG Index Ready")

while True:

    question = input("\nQuestion: ")

    if question.lower() == "exit":
        break

    q_emb = model.encode(
        [question],
        normalize_embeddings=True
    )

    scores, ids = index.search(
        np.array(q_emb).astype("float32"),
        5
    )

    print("\nTop Retrieved Chunks\n")

    for idx in ids[0]:

        row = meta.iloc[idx]

        print("=" * 80)

        print("Document:", row["document"])

        print("Section:", row["section"])

        print(row["text"][:500])

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

KeyboardInterrupt:

In [40]:
import pandas as pd

test = pd.read_csv("test.csv")

def answer_question(row):
    return row["contexts"][:1000]

answers = []

for _, row in test.iterrows():
    answers.append(answer_question(row))

submission = pd.DataFrame({
    "id": test["id"],
    "answer": answers
})

submission.to_csv("submission.csv", index=False)

print("Done")

Done

In [41]:
from google.colab import files

files.download("submission.csv")